base_url = "https://lightclient.io"

theme = "simple-dev-blog"

compile_sass = true
highlight_code = true
build_search_index = false

taxonomies = [
  { name = "tags" }
]

[extra]
nav = []

icon = "icon.png"
profile = "icon.png"

author = "lightclient"

twitter = "@lightclients"
footer_about = ""
not_found_message = "This is not the page you're looking for... return back to [safety?](/)"

katex_enable = true
katex_auto_render = true


