name: Build and deploy GH Pages
on:
  push:
    branches:
      - master
permissions:
  contents: write
jobs:
  build:
    name: Build and deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: shalzz/zola-deploy-action@v0.22.1
      env:
        PAGES_BRANCH: gh-pages
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
